version: '3.8'

services:
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/drillsdb
      SESSION_SECRET: devsecret
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - server

volumes:
  mongo-data:

